config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  # characters
  get '/my_characters', to: 'characters#my_characters', as: 'my_characters'
  get '/characters/new', to: 'characters#new', as: 'new_character'
  post '/characters', to: 'characters#create', as: 'characters'
  get '/characters/:id', to: 'characters#show', as: 'character'

  #campaigns
  get '/my_campaigns', to: 'campaigns#my_campaigns', as: 'my_campaigns'
  post '/campaigns', to: 'campaigns#create', as: 'new_campaign'
  get '/campaigns/:id', to: 'campaigns#show', as: 'campaign'

  #campaign_options
  get '/campaign_options', to: 'campaign_options#index', as: 'campaign_options'

  # campaign_sessions within campaigns
  post '/campaigns/:campaign_id/campaign_sessions', to: 'campaign_sessions#create', as: 'campaign_sessions'
  get '/campaigns/:campaign_id/campaign_sessions/:id', to: 'campaign_sessions#show', as: 'campaign_session'
  post 'campaign_sessions/send_message', to: 'campaign_sessions#send_message'

  # messages
  resources :campaign_sessions, only: :show do
    resources :messages, only: :create
  end

  #invitations
  # post 'campaigns/:campaign_id/invitations', to: 'campaigns#create', as: 'invitations'
  # post '/invitations/:id/accept', to: 'invitations#accept', as: 'accept_invitation'
  # post '/invitations/:id/decline', to: 'invitations#decline', as: 'decline_invitation'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm custom-navbar">
  <!-- Brand/Logo -->
  <ul class="navbar-nav align-items-center">
    <li class="nav-item">
      <%= link_to image_tag('DG_D20.png', alt: 'Logo', class: 'navbar-logo', width: '40', height: '40'), root_path, class: 'nav-link' %>
    </li>
    <% if user_signed_in? %>
        <li class="nav-item">
          <span class="navbar-text">Welcome, <%= current_user.email.split(/@/)[0].capitalize %>!</span>
        </li>
    <% end %>
  </ul>

  <!-- User links -->
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav ms-auto align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Characters", my_characters_path, method: :get, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Campaigns", my_campaigns_path, method: :get, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-link nav-link", form: { class: 'd-inline' } %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= button_to 'Sign In', new_user_session_path, method: :get, class: "btn btn-link nav-link", form: { class: 'd-inline' } %>
        </li> 
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_wizard.html.erb
<div data-controller="wizard" id="wizard-container">
</div>