config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  # characters
  get '/my_characters', to: 'characters#my_characters', as: 'my_characters'
  get '/characters/new', to: 'characters#new', as: 'new_character'
  post '/characters', to: 'characters#create', as: 'characters'
  get '/characters/:id', to: 'characters#show', as: 'character'

  #campaigns
  get '/my_campaigns', to: 'campaigns#my_campaigns', as: 'my_campaigns'
  post '/campaigns', to: 'campaigns#create', as: 'new_campaign'
  get '/campaigns/:id', to: 'campaigns#show', as: 'campaign'

  #campaign_options
  get '/campaign_options', to: 'campaign_options#index', as: 'campaign_options'

  # campaign_sessions within campaigns
  post '/campaigns/:campaign_id/campaign_sessions', to: 'campaign_sessions#create', as: 'campaign_sessions'
  get '/campaigns/:campaign_id/campaign_sessions/:id', to: 'campaign_sessions#show', as: 'campaign_session'
  post 'campaign_sessions/send_message', to: 'campaign_sessions#send_message'

  # messages
  resources :campaign_sessions, only: :show do
    resources :messages, only: :create
  end

  #invitations
  # post 'campaigns/:campaign_id/invitations', to: 'campaigns#create', as: 'invitations'
  # post '/invitations/:id/accept', to: 'invitations#accept', as: 'accept_invitation'
  # post '/invitations/:id/decline', to: 'invitations#decline', as: 'decline_invitation'

end

app/models/character.rb
class Character < ApplicationRecord
  before_validation :set_image_path, on: :create
  before_validation :set_current_hp, on: :create
  before_validation :set_class_defaults, on: :create
  before_validation :set_default_level, on: :create
  belongs_to :user
  belongs_to :race
  belongs_to :character_class
  has_many :campaigns
  has_and_belongs_to_many :spells, join_table: 'character_spells'
  has_and_belongs_to_many :stats, join_table: 'character_stats'
  serialize :equipment, Array
  serialize :languages, Array

  validates :name, :level, :race, :character_class, :max_hp, :current_hp, :armor_class, :equipment, presence: true

    def set_image_path
      image_lookup = {
        "male_tiefling_warlock" => "male_tiefling_warlock.png",
        "female_tiefling_warlock" => "female_tiefling_warlock.png",
        "male_woodelf_druid" => "male_woodelf_druid.png",
        "female_woodelf_druid" => "female_woodelf_druid.png",
        "male_dragonborn_fighter" => "male_dragonborn_fighter.png",
        "female_dragonborn_fighter" => "female_dragonborn_fighter.png",
        "male_hilldwarf_cleric" => "male_hilldwarf_cleric.png",
        "female_hilldwarf_cleric" => "female_hilldwarf_cleric.png",
        "male_dragonborn_druid" => "male_dragonborn_druid.png",
        "female_dragonborn_druid" => "female_dragonborn_druid.png",
        "male_woodelf_fighter" => "male_woodelf_fighter.png",
        "female_woodelf_fighter" => "female_woodelf_fighter.png",
        "male_woodelf_cleric" => "male_woodelf_cleric.png",
        "female_woodelf_cleric" => "female_woodelf_cleric.png"
      }

      key_base = "#{self.race.name.downcase.gsub(' ', '')}_#{self.character_class.name.downcase}"
      gender_key = self.gender.downcase
      gender_key = ["male", "female"].sample if gender_key == 'other'
      
      full_key = "#{gender_key}_#{key_base}"
      
      self.image_path = image_lookup[full_key]
    end


  private

  def set_class_defaults

    stats_values = {}

    case self.character_class.name.downcase
    when 'cleric'
      self.max_hp = 10
      self.armor_class = "Heavy Armor"
      self.equipment = ["Chain Mail", "Shield", "Mace", "Holy Symbol", "Adventurer's Pack"]
      self.languages = ["Common", "Celestial"]

    when 'warlock'
      self.max_hp = 9
      self.armor_class = "Medium Armor"
      self.equipment = ["Leather Armor", "Dagger", "Spellbook", "Component Pouch", "Adventurer's Pack"]
      self.languages = ["Common", "Infernal"]

    when 'druid'
      self.max_hp = 9
      self.armor_class = "Medium Armor"
      self.equipment = ["Hide Armor", "Wooden Shield", "Scimitar", "Druidic Focus", "Adventurer's Pack"]
      self.languages = ["Common", "Elvish", "Druidic"]

    when 'fighter'
      self.max_hp = 12
      self.armor_class = "Heavy Armor"
      self.equipment = ["Chain Mail", "Longsword", "Shield", "Crossbow", "Adventurer's Pack"]
      self.languages = ["Common", "Dwarvish"]
    end
  end

  def stats_defaults
    case self.character_class.name.downcase

    when 'cleric'
      stats_values = {
        "Strength" => 12,
        "Dexterity" => 10,
        "Constitution" => 14,
        "Intelligence" => 10,
        "Wisdom" => 15,
        "Charisma" => 13
      }

    when 'warlock'
      stats_values = {
        "Strength" => 8,
        "Dexterity" => 12,
        "Constitution" => 13,
        "Intelligence" => 14,
        "Wisdom" => 10,
        "Charisma" => 16
      }

    when 'druid'
      stats_values = {
        "Strength" => 10,
        "Dexterity" => 12,
        "Constitution" => 12,
        "Intelligence" => 14,
        "Wisdom" => 16,
        "Charisma" => 9
      }

    when 'fighter'
      stats_values = {
        "Strength" => 16,
        "Dexterity" => 13,
        "Constitution" => 14,
        "Intelligence" => 10,
        "Wisdom" => 11,
        "Charisma" => 8
      }
    end
  end

  def set_current_hp
    self.current_hp = self.max_hp
  end

  def set_default_level
    self.level ||= 1
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!

  def my_characters
    @user = current_user
    @characters = @user.characters
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # POST /characters
  def create
    @character = Character.new(character_params)
    @character.user = current_user

    if @character.valid?
      set_character_stats(@character)
    end

    if @character.save
      redirect_to my_characters_path
    else
      render :new
    end
  end

  # GET /characters/:id
  def show
    @character = Character.find(params[:id])
  end

  private

  def set_character_stats(character)
    stats_values = character.send(:stats_defaults)

    stats_values.each do |name, value|
      stat = Stats.find_or_create_by(name: name)
      CharacterStats.create!(character: character, stats_id: stat.id, value: value)
    end
  end

  # strong parameters for character
  def character_params
    params.require(:character).permit(:user, :name, :level, :race_id, :character_class_id, :max_hp, :current_hp, :armor_class, :gender, :languages, :equipment)
  end
end

app/views/characters/my_characters.html.erb
<div class="character-card-container">
  <% if @characters.any? %>
    <% @characters.each do |character| %>
      <div class="character-flip-card">
        <div class="character-flip-card-inner">
          <!-- Card Front -->
          <div class="character-flip-card-front">
            <figure>
              <%= image_tag(character.image_path) if character.image_path.present? %>
              <figcaption><%= character.name %></figcaption>
            </figure>
          </div>
          <!-- Card Back -->
          <div class="character-flip-card-back">
            <div class="character-image" style="background-image: url('<%= asset_path(character.image_path) if character.image_path.present? %>');"></div>
            <div class="character-details">
              <ul class="no-bullets bold-list">
                <p><strong><span class="level-circle"><%= character.level %></span> <span class="interpolated"><%= character.race.name %></span> <span class="interpolated"><%= character.character_class.name %></span></strong></p>
                <li>Gender: <span class="interpolated"><%= character.gender.capitalize %></span></li>
                <li>HP: <span class="interpolated"><%= character.current_hp %>/<%= character.max_hp %></span></li>
                <li>Armor Class: <span class="interpolated"><%= character.armor_class %></span></li>
                <li>Equipment: <span class="interpolated"><%= character.equipment.join(', ') if character.equipment %></span></li>
                <li>Languages: <span class="interpolated"><%= character.languages.join(', ') if character.languages %></span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You currently have no characters.</p>
  <% end %>
</div>
<%= link_to new_character_path, class: "circle-add-btn-link" do %>
  <button class="circle-add-btn">+</button>
<% end %>

app/views/characters/new.html.erb
<div class="name-gen-container">
  <h3>Let The Dice Decide Your One True Name</h3>
  <br>
  <form class="name-gen-form"> 
    <select id='race' name="race">
      <option value="elven">Elven</option>
      <option value="dwarven">Dwarven</option>
      <option value="dragonborn">Dragonborn</option>
      <option value="tiefling">Tiefling</option>
    </select>
    <select id='class' name="class">
      <option value="fighter">Fighter</option>
      <option value="warlock">Warlock</option>
      <option value="cleric">Cleric</option>
      <option value="druid">Druid</option>
    </select>
    <button id='submit' type="button">
    <i class="fa-solid fa-dice-d20 fa-shake fa-xl" style="color: #9900ff;"></i>
  </button>
  </form>
  <div id='nameArea'>
  </div>
</div>

<%= form_with(model: @character, local: true, html: { class: "new-character-form" }) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
      <ul>
        <% @character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Name</h4>
  <div class="form-field">
    <h4><label for="character_name">Name</label></h4>
    <%= f.text_field :name, id: "character_name" %>
  </div>
  <br>
  <h4>Race</h4>
  <div class="form-field race-class-container">
    <h4><%= f.label :race %></h4>
    <% Race.all.each do |r| %>
      <button type="button" class="race-button glass-button-char" data-id="<%= r.id %>"><%= r.name %></button>
      <div class="form-hover-info">
        <h2> <%= r.name %> </h2>
        <p><%= r.description %></p>
        <strong> Ability bonuses:</strong>
        <p><%= r.ability_bonuses %></p>
        <strong> Traits:</strong>
        <p><%= r.traits %></p>
        <strong> Languages:</strong>
        <p><%= r.languages %></p>
      </div>
    <% end %>
    <%= f.hidden_field :race_id, id: "hidden_race_id" %>
  </div>
  <br>
  <h4>Class</h4>
  <div class="form-field character-class-container">
    <h4><%= f.label :character_class %></h3>
    <% CharacterClass.all.each do |c| %>
      <button type="button" class="character-class-button glass-button-char" data-id="<%= c.id %>"><%= c.name %></button>
      <div class="form-hover-info">
        <h2><%= c.name %></h2>
        <p><%= c.description %></p>
        <div class="ability-info">
          <div class="ability-section">
            <strong>Hit die:</strong>
            <p><%= c.hit_die %></p>
          </div>
          <div class="ability-section">
            <strong>Primary ability:</strong>
            <p><%= c.primary_ability %></p>
          </div>
          <div class="ability-section">
            <strong>Spellcasting ability:</strong>
            <p><%= c.spellcasting_ability %></p>
          </div>
        </div>
      </div>
    <% end %>
    <%= f.hidden_field :character_class_id, id: "hidden_character_class_id" %>
  </div>
  <br>
  <h4>Gender</h4>
  <div class="form-field gender-container">
    <h4><%= f.label :gender %></h4>
    <button type="button" class="gender-button glass-button-char" data-id="Female">Female</button>
    <button type="button" class="gender-button glass-button-char" data-id="Male">Male</button>
    <button type="button" class="gender-button glass-button-char" data-id="Non-Binary">Non-Binary</button>
    <button type="button" class="gender-button glass-button-char" data-id="Other">Other</button>
    <%= f.hidden_field :gender, id: "hidden_gender_id" %>
  </div>

  <br>
  <center><div class="actions">
    <%= f.submit "Create Character", class: "glass-button-select", style: "width: 200px;" %>
  </div></center>
<% end %>


<script>
console.log('start');
const submitButton = document.getElementById('submit');
console.log('button assigned');
const nameArea = document.getElementById('nameArea');

let beginningName = '';
let middleName = '';
let endName = '';
let title = '';
let epithet = '';

const elvenBeginning = ['Fa', 'Syl'];
const elvenMiddle = ['lews', 'sis'];
const elvenEnd = ['llyn', 'na'];

const dwarvenBeginning = ['Yo', 'Bi'];
const dwarvenMiddle = ['no', 'gan'];
const dwarvenEnd = ['minor', 'ithor'];

const wealdBeginning = ['Al', 'Ro'];
const wealdMiddle = ['g', 'th'];
const wealdEnd = ['ar', 'an'];

const tieflingBeginning = ['Br'];
const tieflingMiddle = ['i'];
const tieflingEnd = ['an'];

const warriorTitle = ['War Ender', 'Battlelord', 'Knight', 'Brawler', 'Blood Tyrant'];
const warriorEpithet = [', The Brave', ', The Bold', ', The Slaughterer'];

const wizardTitle = ['Sage', 'Archmage', 'Mage', 'Wizard', 'Necromancer'];
const wizardEpithet = [', The Enlightened', ', Dragon Speaker', ', The Eldritch'];

const trollTitle = ['Sexy', 'Glamorous', 'Foxy', 'Warmhearth'];
const trollEpithet = [', The Baddie'];

const druidTitle = ['Ethereal', 'Eternal', 'Lycan'];
const druidEpithet = [', The Wise', ', The Defiant', ', The Rebel', ', Mystical Protector', ', Forest Protector', ', Beast King'];
console.log('variables assigned');

function randomIntFromInterval(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

submitButton.addEventListener('click', function () {
  console.log('submitted');

  // Clear existing names
  nameArea.innerHTML = '';

  let raceDropDown = document.getElementById("race");
  let race = raceDropDown.options[raceDropDown.selectedIndex].value;
  let myClass = document.getElementById('class').value;

  if (race == 'elven') {
    beginningName = elvenBeginning[randomIntFromInterval(1, elvenBeginning.length) - 1];
    middleName = elvenMiddle[randomIntFromInterval(1, elvenMiddle.length) - 1];
    endName = elvenEnd[randomIntFromInterval(1, elvenEnd.length) - 1];
  }
  if (race == 'dragonborn') {
    beginningName = wealdBeginning[randomIntFromInterval(1, wealdBeginning.length) - 1];
    middleName = wealdMiddle[randomIntFromInterval(1, wealdMiddle.length) - 1];
    endName = wealdEnd[randomIntFromInterval(1, wealdEnd.length) - 1];
  }

  if (race == 'dwarven') {
    beginningName = dwarvenBeginning[randomIntFromInterval(1, dwarvenBeginning.length) - 1];
    middleName = dwarvenMiddle[randomIntFromInterval(1, dwarvenMiddle.length) - 1];
    endName = dwarvenEnd[randomIntFromInterval(1, dwarvenEnd.length) - 1];
  }

  if (race == 'tiefling') {
    beginningName = tieflingBeginning[randomIntFromInterval(1, tieflingBeginning.length) - 1];
    middleName = tieflingMiddle[randomIntFromInterval(1, tieflingMiddle.length) - 1];
    endName = tieflingEnd[randomIntFromInterval(1, tieflingEnd.length) - 1];
  }

  if (myClass == 'warlock') {
    title = wizardTitle[randomIntFromInterval(1, wizardTitle.length) - 1];
    epithet = wizardEpithet[randomIntFromInterval(1, wizardEpithet.length) - 1];
  }

  if (myClass == 'fighter') {
    title = warriorTitle[randomIntFromInterval(1, warriorTitle.length) - 1];
    epithet = warriorEpithet[randomIntFromInterval(1, warriorEpithet.length) - 1];
  }
  if (myClass == 'cleric') {
    title = trollTitle[randomIntFromInterval(1, trollTitle.length) - 1];
    epithet = trollEpithet[randomIntFromInterval(1, trollEpithet.length) - 1];
  }

  if (myClass == 'druid') {
    title = druidTitle[randomIntFromInterval(1, druidTitle.length) - 1];
    epithet = druidEpithet[randomIntFromInterval(1, druidEpithet.length) - 1];
  }

  let myName = title + ' ' + beginningName + middleName + endName;

  if (epithet.startsWith(',')) {
    myName += epithet; 
  } else {
    myName += ' ' + epithet; 
  }

  let fantasyName = document.createElement('li');
  fantasyName.textContent = myName;

  nameArea.append(fantasyName);
  console.log('fantasyName appended');
});
</script>

<script>
document.addEventListener("DOMContentLoaded", function() {
  // For character classes
  document.querySelectorAll('.character-class-button').forEach(function(button) {
    button.addEventListener('click', function(e) {
      // Remove the 'button-selected' class from all other buttons in the group
      document.querySelectorAll('.character-class-button').forEach(function(otherButton) {
        otherButton.classList.remove('button-selected');
      });

      // Add the 'button-selected' class to the clicked button
      e.target.classList.add('button-selected');

      // Update the hidden field value
      document.getElementById("hidden_character_class_id").value = e.target.dataset.id;
    });
  });

  // For races
  document.querySelectorAll('.race-button').forEach(function(button) {
    button.addEventListener('click', function(e) {
      // Remove the 'button-selected' class from all other buttons in the group
      document.querySelectorAll('.race-button').forEach(function(otherButton) {
        otherButton.classList.remove('button-selected');
      });

      // Add the 'button-selected' class to the clicked button
      e.target.classList.add('button-selected');

      // Update the hidden field value
      document.getElementById("hidden_race_id").value = e.target.dataset.id;
    });
  });

  // New code for gender
  document.querySelectorAll('.gender-button').forEach(function(button) {
    button.addEventListener('click', function(e) {
      // Remove the 'button-selected' class from all other buttons in the group
      document.querySelectorAll('.gender-button').forEach(function(otherButton) {
        otherButton.classList.remove('button-selected');
      });

      // Add the 'button-selected' class to the clicked button
      e.target.classList.add('button-selected');

      // Update the hidden field value
      document.getElementById("hidden_gender_id").value = e.target.dataset.id;
    });
  });
});
</script>