config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  # characters
  get '/my_characters', to: 'characters#my_characters', as: 'my_characters'
  get '/characters/new', to: 'characters#new', as: 'new_character'
  post '/characters', to: 'characters#create', as: 'characters'
  get '/characters/:id', to: 'characters#show', as: 'character'

  #campaigns
  get '/my_campaigns', to: 'campaigns#my_campaigns', as: 'my_campaigns'
  post '/campaigns', to: 'campaigns#create', as: 'new_campaign'
  get '/campaigns/:id', to: 'campaigns#show', as: 'campaign'

  #campaign_options
  get '/campaign_options', to: 'campaign_options#index', as: 'campaign_options'

  # campaign_sessions within campaigns
  post '/campaigns/:campaign_id/campaign_sessions', to: 'campaign_sessions#create', as: 'campaign_sessions'
  get '/campaigns/:campaign_id/campaign_sessions/:id', to: 'campaign_sessions#show', as: 'campaign_session'
  post 'campaign_sessions/send_message', to: 'campaign_sessions#send_message'

  # messages
  resources :campaign_sessions, only: :show do
    resources :messages, only: :create
  end

  #invitations
  # post 'campaigns/:campaign_id/invitations', to: 'campaigns#create', as: 'invitations'
  # post '/invitations/:id/accept', to: 'invitations#accept', as: 'accept_invitation'
  # post '/invitations/:id/decline', to: 'invitations#decline', as: 'decline_invitation'

end

app/models/campaign_option.rb
class CampaignOption < ApplicationRecord
  has_many :campaigns
end

app/controllers/campaign_options_controller.rb
class CampaignOptionsController < ApplicationController
  def index
    @campaign_options = CampaignOption.includes(campaigns: :character).all
    @characters = current_user.characters
  end
end

app/views/campaign_options/index.html.erb
<div class="campaign-card-container">
  <% if @campaign_options.any? %>
    <% @campaign_options.each do |campaign| %>
      <div class="campaign-card">
        <div class="face face1">
          <div class="campaign-figure">
            <div class="img-container">
              <%= image_tag campaign.image_url %>
            </div>
          </div>
          <div class="campaign-figcaption"><%= campaign.name %></div>
        </div>

        <div class="face face2">
          <div class="campaign-content">
            <%= campaign.description %>
          </div>
          <br>
          <!-- Start of form -->
          <div class="character-selection-wrapper">
            <strong>Choose your character:</strong>
            <%= form_with url: new_campaign_path, method: :post, class: "select-campaign-form" do %>
              <%= hidden_field_tag :campaign_id, campaign.id %>
              <% if @characters && @characters.any? %>
                <%= select_tag :character_id, options_from_collection_for_select(@characters, "id", "name") %>
              <% else %>
                <p>You currently have no characters.</p>
              <% end %>
          </div>
            <br>
            <%= submit_tag 'Select Campaign', class: "glass-button-select" %>
          <% end %>
          <!-- End of form -->
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You currently have no campaigns.</p>
  <% end %>
</div>