config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  # characters
  get '/my_characters', to: 'characters#my_characters', as: 'my_characters'
  get '/characters/new', to: 'characters#new', as: 'new_character'
  post '/characters', to: 'characters#create', as: 'characters'
  get '/characters/:id', to: 'characters#show', as: 'character'

  #campaigns
  get '/my_campaigns', to: 'campaigns#my_campaigns', as: 'my_campaigns'
  post '/campaigns', to: 'campaigns#create', as: 'new_campaign'
  get '/campaigns/:id', to: 'campaigns#show', as: 'campaign'

  #campaign_options
  get '/campaign_options', to: 'campaign_options#index', as: 'campaign_options'

  # campaign_sessions within campaigns
  post '/campaigns/:campaign_id/campaign_sessions', to: 'campaign_sessions#create', as: 'campaign_sessions'
  get '/campaigns/:campaign_id/campaign_sessions/:id', to: 'campaign_sessions#show', as: 'campaign_session'
  post 'campaign_sessions/send_message', to: 'campaign_sessions#send_message'

  # messages
  resources :campaign_sessions, only: :show do
    resources :messages, only: :create
  end

  #invitations
  # post 'campaigns/:campaign_id/invitations', to: 'campaigns#create', as: 'invitations'
  # post '/invitations/:id/accept', to: 'invitations#accept', as: 'accept_invitation'
  # post '/invitations/:id/decline', to: 'invitations#decline', as: 'decline_invitation'

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  belongs_to :campaign_option
  has_many :campaign_sessions, dependent: :destroy
  belongs_to :character
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  def my_campaigns
    @user = current_user
    @campaigns = @user.campaigns
    @campaign_options = @campaigns.map do |campaign|
      campaign.campaign_option
    end
  end

  def create
    @option = CampaignOption.find(params[:campaign_id])
    @character = Character.find(params[:character_id])
    
    @campaign = Campaign.new(
      user: current_user,
      campaign_option: @option,
      character: @character
    )
    
    if @campaign.save
      redirect_to campaign_path(@campaign.id)
    else
      render :new
    end
  end

  def show
    @campaign = Campaign.find(params[:id])
    @existing_session = CampaignSession.where(campaign_id: @campaign.id).last
  end

  private

  def campaign_params
    params.require(:campaign).permit(:user, :name, :location, :description)
  end
end

app/views/campaigns/my_campaigns.html.erb
<div class="mycampaigns-container">
  <% if @campaign_options.any? %>
    <% @campaign_options.each do |campaign_option| %>
      <% campaign_option.campaigns.each do |campaign| %> <!-- Loop through campaigns -->
        <%= link_to campaign_path(campaign.id), class: 'card-link' do %>
          <div class="mycampaigns-card">
            <div class="mask"></div>
            <div class="character-profile-picture">
              <% if campaign.character&.image_path %>
                <%= image_tag campaign.character.image_path, class: "profile-pic" %>
              <% end %>
            </div>
            <!-- Campaign Image and Name -->
            <div class="mycampaigns-image">
              <%= image_tag campaign_option.image_url %>
              <div class="campaign-name-overlay">
                <%= campaign_option.name %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %> <!-- End of campaigns loop -->
    <% end %>
  <% else %>
    <p>You currently have no campaigns.</p>
  <% end %>
</div>

<%= link_to campaign_options_path, class: "circle-add-btn-link" do %>
  <button class="circle-add-btn">+</button>
<% end %>

app/views/campaigns/new.html.erb
<div class="main-content">
  <div class="new-campaign-container">
    <div class="new-campaign-form-content">
      <%= form_with(model: @campaign, local: true, html: { class: "new-campaign-form" }) do |f| %>

        <div class="form-field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="form-field">
          <%= f.label :location %>
          <%= f.text_field :location %>
        </div>

        <div class="form-field">
          <%= f.label :description %>
          <%= f.text_field :description %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="campaign-show">
  <h2><%= @campaign.campaign_option.name %></h2>

  <div class="show-image-container">
    <div class="img-show">
      <%= image_tag @campaign.campaign_option.image_url %>
    </div>

    <div class="profile-pic-container">
      <%= image_tag @campaign.character.image_path, class: "show-profile-pic" %>
    </div>
  </div>
    
    <h3><%= @campaign.character.name %>, are you ready?...</h3>
    
    <% if @existing_session.nil? %>
      <%= button_to 'Begin Campaign', campaign_sessions_path(@campaign), class: "glass-button" %>
    <% else %>
      <%= button_to 'Continue Campaign', campaign_session_path(@campaign, @existing_session), class: "glass-button", method: :get %>
    <% end %>
  </div>
</div>